
services:
  eureka:
    build: ./Eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - hotel-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - eureka
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
    networks:
      - hotel-network

  hotel-service:
    build: ./hotelService
    container_name: hotel-service
    depends_on:
      - eureka
      - mysql
    ports:
      - "5000:5000"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hoteldb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - hotel-network

  reservation-service:
    build: ./reservationService
    container_name: reservation-service
    depends_on:
      - eureka     
      - mysql
    ports:
      - "6000:6000"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hotelReservations?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - hotel-network
    

  auth-service:
    build: ./auth
    container_name: auth-service
    depends_on:
      - eureka
      - mysql
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/authdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - hotel-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hoteldb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hotel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - hotel-network
  
  # NOU SERVEI DE FRONTEND (REACT)
  ui-service:
    build: ./ui-service
    container_name: ui-service
    ports:
      # L'usuari visitarà localhost:3000
      # El port intern de Nginx és el 80
      - "3000:80"
    depends_on:
      - api-gateway  # S'espera a que l'API Gateway s'iniciï
    networks:
      - hotel-network

volumes:
  mysql_data:

networks:
  hotel-network:
    driver: bridge