server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # RUTA cap a HOTEL-SERVICE
        - id: HOTEL-SERVICE
          # "lb" significa Load Balancer. L'API Gateway
          # preguntarà a Eureka on és "HOTEL-SERVICE"
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**, /css/**, /js/**, /images/**

# --- Configuració d'Eureka ---
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # Aquesta és la línia clau:
      # 1. Intenta llegir la variable d'entorn de Docker.
      # 2. Si no la troba, fa servir 'localhost' (per a proves locals).
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  
  instance:
    # Això és millor per a Docker/Eureka.
    # Es registrarà amb el nom de l'aplicació (api-gateway)
    hostname: ${spring.application.name}
    prefer-ip-address: true

# Exposar els 'actuator endpoints' (útil per a depuració)
management:
  endpoints:
    web:
      exposure:
        include: "*"